#!/bin/sh

#DEBHELPER#

set -e

case "${1}" in
	configure)

		if [ ! -L /usr/bin/wp ]
		then
			ln -s /usr/share/php/WP_CLI/vendor/wp-cli/wp-cli/bin/wp /usr/bin/wp
		fi

		if [ -e /usr/share/php/WP_CLI/utils/wp-completion.bash ]
		then
			echo "source /usr/share/php/WP_CLI/utils/wp-completion.bash" \
		 	 > /etc/profile.d/wp-completion.sh
		fi

		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)

		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

exit 0
